COMMAND_HELP = {
    "NOOP": "NOOP - No operation (keep connection alive).",
    "HELP": "HELP [command] - Show help information.",
    "QUIT": "QUIT - Close the current session.",
    "SYST": "SYST - Return system type.",
    "USER": "USER <username> - Specifies the username for authentication.",
    "PASS": "PASS <password> - Sends the password for authentication. Must follow USER command.",
    "REIN": "REIN - Reinitialize session: resets authentication, cwd, renaming, and passive mode.",
    "TYPE": "TYPE <A|I|E|L> - Set transfer type: ASCII, Binary, EBCDIC, or Local.",
    "PWD" : "PWD - Print the current working directory.",
    "CWD" : "CWD <directory> - Change the current working directory.",
    "CDUP": "CDUP - Change to parent directory.",
    "MKD" : "MKD <directory> - Create a new directory.",
    "RMD" : "RMD <directory>  Remove an empty directory.",
    "DELE": "DELE <file>  Delete a file from the current directory.",
    "RNFR": "RNFR <path>  Begin renaming a file or directory. Must be followed by RNTO.",
    "RNTO": "RNTO <name> — Completes a rename operation started with RNFR.",
    "STAT": "STAT [path] - Muestra información sobre la sesión si no se especifica ruta, o información de un archivo/directorio si se proporciona <path>.",
    "PASV": "Enter Passive Mode. Opens a data connection port for file transfers (LIST, RETR, STOR). The server will respond with the IP and port to connect.",
    "LIST": "LIST [<path>] - Lista archivos y directorios en el path especificado (detailed). Si no se pasa path, se asume el directorio actual.",
    "NLST": "NLST [<path>] - Lista solo los nombres de archivos y directorios en el path especificado. Si no se pasa path, se asume el directorio actual.",
    "STOR": "STOR <filename>  - Upload a file from client to server. Initiates data transfer to store the specified file in the current directory.",
    "RETR": "RETR <filename>  - Retrieve a file from server to client. Initiates data transfer to download the specified file from the current directory."
}
